version: "3.7"
services:
  mysql:
    image: mysql/mysql-server:5.7.37
    environment:
      MYSQL_DATABASE: market
      MYSQL_USER: tempuser
      MYSQL_PASSWORD: saxud3sldnbsdfsdf
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: tempuser
      PMA_PASSWORD: saxud3sldnbsdfsdf
    ports:
      - "8080:80"
  legacy-php:
    depends_on:
      - mysql
    image: php:5.3.29-apache
    volumes:
      - .:/var/www/html/
    ports:
      - "8000:80"
